
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    command: pipenv run python client.py
