
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
        - "27017:27017"
        volumes:
        - ./mongodb_data:/data/mongodb
        
    flask-app:
        build:
            context: .
        container_name: flask-app
        ports:
        - "5001:5001"
        depends_on:
        - mongodb
        environment:
        - MONGO_URI=mongodb://mongodb:27017
        - FLASK_PORT=5001
